Cafeteria_manager/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  put "menus/edit_menu_details" => "menus#edit_menu_details", as: :edit_menu_details
  put "menu_item/edit_menu_items_details" => "menu_items#edit_menu_item_details", as: :edit_menu_item_details
  get "admin/manage_billers" => "admin#manage_billers", as: :manage_billers
  get "admin/new_clerk" => "admin#new_clerk", as: :new_clerk
  post "admin/create_clerk" => "admin#create_clerk", as: :create_clerk
  get "admin/users" => "admin#users", as: :show_users
  get "admin/reports" => "admin#reports", as: :show_reports
  delete "admin/delete_user" => "admin#delete_user", as: :delete_user
  patch "admin/role_clerk" => "admin#role_change_clerk", as: :role_change_clerk
  patch "admin/role_customer" => "admin#role_change_customer", as: :role_change_customer
  resources :menu_items
  resources :menus
  resources :users
  get "/orders/pending" => "orders#pending", as: :pending_orders
  resources :orders
  resources :admin
  resources :order_items
  get "/" => "home#index"
  post "/cart" => "orders#cart"
  get "/active" => "menus#active_menus", as: :active_menus
  post "/signin" => "sessions#create", as: :sessions
  get "/signin" => "sessions#new", as: :new_sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

Cafeteria_manager/app/models/menu.rb
class Menu < ActiveRecord::Base
  validates :menu_name, presence: true
  validates :menu_name, length: { minimum: 2 }
  has_many :menu_items, dependent: :destroy

  def self.active
    all.where(active: true)
  end
end

Cafeteria_manager/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @current_user = current_user
    @menus = Menu.active
    render "index"
  end

  def new
    render "new"
  end

  def show
    if @current_user == nil
      @current_user = current_user
    end
    render "show"
  end

  def create
    name = params[:menu_name]
    new_menu = Menu.new(menu_name: name, active: false)
    if new_menu.save
      redirect_to new_menu_path
    else
      flash[:error] = new_menu.errors.full_messages.join(",")
      redirect_to new_menu_path
    end
  end

  def destroy
    id = params[:id]
    Menu.find(id).destroy
    redirect_to new_menu_path
  end

  def edit
    id = params[:id]
    session[:edit_menu_id] = id
    redirect_to new_menu_path
  end

  def update
    id = params[:id]
    menu = Menu.find(id)
    menu.active = !menu.active
    menu.save!
    redirect_to new_menu_path
  end

  def active_menus
    render "active"
  end

  def edit_menu_details
    id = params[:menu_id]
    new_name = params[:menu_name]
    menu = Menu.find(id)
    menu.menu_name = new_name
    if menu.save
      session[:edit_menu_id] = -1
    else
      flash[:error] = menu.errors.full_messages.join(",")
    end
    redirect_to new_menu_path
  end
end

Cafeteria_manager/app/views/menus/_menu_item_section.html.erb
<section class="MenuItem">
  <%= form_with url: orders_path, method: "post" do |form| %>
    <% menu.each do |item| %>
      <li>
        <div class="MenuItem-container">
          <%= form.check_box :item_ids, {multiple: true, id: "item-#{item.id}"}, item.id, nil %>
          <label for="<%= "item-#{item.id}" %>"><%= item.menu_item_name %> </label>
          <p class="MenuItem-price"> <%=item.menu_item_price%> </p>
          <%= link_to menu_item_path(item.id) ,method: "delete" do %>
              <%= image_tag ('trash-can.svg') %>
          <% end %>
        </div>
      </li>
    <% end %>
    <%= form.submit "Add to Cart" %>
    <%= form.submit "Place Order" %>
  <% end %>
</section>

Cafeteria_manager/app/views/menus/index.html.erb
<% color = Array['#4dd0e1','#ffd54f','#e0e0e0','#9575cd'] %>
<% counter = 0 %>
<article>
  <p class="ChangeFont">Menus</p>
    <div class="Menu-grid">
    <% @menus.each do |menu| %>
        <%= link_to menu_path(menu.id), class: "Menu-link" do %>
          <label class="Menu-container">
            <p class="Menu-text" style="background-color: <%= color[counter] %> "> <%= menu.menu_name %> </p>
          </label>
        <% end %>
        <% counter = counter + 1 %>
    <% end %>
      </div>
</article>

Cafeteria_manager/app/views/menus/new.html.erb
<article>
  <div>
    <%= form_with(url:'/menus',method: 'post', class: "AddMenu") do %>
      <%= text_field_tag 'menu_name', nil, placeholder: 'Name of the Menu?', class: "AddMenu-name" %>
      <%= submit_tag 'Add',class:'AddMenu-button' %>
    <%end%>
  </div>
  <div class="Menus">
    <%Menu.all.each do |menu|%>
        <% if session[:edit_menu_id].to_s == (menu.id).to_s %>
          <div class="EditMenu">
            <%= form_with url:edit_menu_details_path, method: 'put' do %>
              <%= hidden_field_tag :menu_id, menu.id %>
              <%= text_field_tag 'menu_name', menu.menu_name, placeholder: 'Change the Menu Name', class:"AddMenu-name"%>
              <%= submit_tag "change name", class:"Table-button" %>
            <% end %>
          </div>
        <% else %>
            <div class="EditMenu">
              <%= link_to menu_path(menu.id), method:"put" do %>
                <%= check_box_tag 'active', '1', checked = menu.active, class: 'Menu-checkbox', onclick: 'this.form.submit()' %>
              <% end %>
              <p class="EditMenu-name"> <%= menu.menu_name %> </p>
              <%= form_with( url:edit_menu_path(menu.id), method: "get", local: true) do %>
                <%= image_submit_tag 'edit.svg', class:'edit', title: "Edit MenuName" %>
              <% end %>
              <% if menu.active %>
                <p class="Menu-active">Active</p>
              <% else %>
                <p class="Menu-Inactive">InActive</p>
              <% end %>
              <%= form_with( url:menu_item_path(menu.id), method:"get", local:true) do %>
                <%= image_submit_tag 'plus-solid.svg', class: 'plus-img', title: "Edit Menu content" %>
              <% end %>
              <%= form_with url:menu_path(menu.id), method:"delete",class:"Menu-form"  do |form| %>
                <%= image_submit_tag 'trash-can.svg', data: {confirm: "Are you sure?"}, class: "EditMenu-img", title:"Delete Menu" %>
              <% end %>
            </div>
        <% end %>
    <%end%>
  </div>
</article>

Cafeteria_manager/app/views/menus/show.html.erb
<% menu = Menu.find(params[:id]).menu_items %>
<% menu_id = params[:id] %>
<article class="Wrapper">
    <section class="Wrapper-grid">
      <section class="MenuItem">
          <% menu.each do |item| %>
            <div class="MenuItem-container">
              <%= form_with url: cart_path, method: "post" do |form| %>
                <%= hidden_field_tag :item_name, item.menu_item_name %>
                <%= hidden_field_tag :item_price, item.menu_item_price %>
                <%= hidden_field_tag :menu_item_id, item.id %>
                <%= hidden_field_tag :menu_id, menu_id %>
                <p class="MenuItem-name HeaderFont"> <%= item.menu_item_name %> </p>
                <div class="LeftRight">
                <p class="MenuItem-price"> Price: &#x20b9; <%=item.menu_item_price %> </p>
                <div style="display:flex;">
                  <p style="margin-right:10px;">Quantity: </p>
                  <input type="number" name="quantity" id="quantity" value="1" min="1" max="8">
                </div>
                </div>
                <div class="wrapper">
                  <%= form.submit  "Add to Cart", class:"Table-button" %>
                </div>
              <% end %>
            </div>
          <% end %>
      </section>
      <section class="Food-cart">
        <h1 style="font-size:x-large;padding-bottom:10px;" class="HeaderFont">Your Food Cart!</h1>
        <% order_items=Order.find(@current_order.id).order_items %>
        <% total_price=0 %>
        <div class="Item-info">
          <% if order_items.length !=0 %>
              <p class="HeaderFont">S.No</p>
              <p class="HeaderFont">Item</p>
              <p class="HeaderFont">Price</p>
              <p class="HeaderFont">Quantity</p>
              <p class="HeaderFont">Total Price</p>
              <p></p>
          <% end %>
          <% item_count = 1 %>
          <% order_items.each do |item| %>
              <p> <%= item_count %> </p>
              <p> <%= item.menu_item_name %> </p>
              <p> &#x20b9; <%= item.menu_item_price %> </p>
              <p> <%= item.quantity %> </p>
              <p> &#x20b9; <%= item.price %> </p>
              <%= form_with url: order_item_path(item.id), method:"delete"  do%>
                <%= hidden_field_tag :menu_id, menu_id %>
                <%= image_submit_tag 'minus.svg', class:"Minus" %>
              <% end %>
            <% item_count = item_count + 1 %>
            <% total_price += item.price %>
          <% end %>
        </div>
        <% if order_items.length != 0 %>
          <p style="padding:10px;">Total Price: &#x20b9; <%= total_price %> </p>
          <%= form_with url:orders_path, method: "post" do |form| %>
            <%= hidden_field_tag :total_price, total_price %>
            <%= submit_tag value = "Buy Now",
                           data: {confirm: "Confirm Order?", disable_with: "Placing Order.."},
                           class: "Table-button" %>
          <% end %>
        <% else %>
          <p>Add Your Items here..!</p>
        <% end %>
      </section>
    </section>
</article>